Improve duplicity helper
* Read a config specific to its installed name, so we can use
  same script for different (eg hourly, daily) sets
* Handle 'recover' option better
* Only cover a limited set of the duplicity commands -- recovery focussed.
* Good usage output
* README
* CHANGELOG

diff --git a/backupninja/files/duplicity_helper b/backupninja/files/duplicity_helper
--- a/backupninja/files/duplicity_helper
+++ b/backupninja/files/duplicity_helper
@@ -1,7 +1,38 @@
 #!/bin/sh
 
-if [ -r /usr/local/etc/duplicity_helper.conf ]; then
-  . /usr/local/etc/duplicity_helper.conf
+name=$(basename $0 )
+conf_file="/usr/local/etc/${name}.conf"
+
+if [ -r $conf_file ]; then
+  . $conf_file
+else
+  echo "Could not read config file '${conf_file}'. Aborting."
+  exit 1
 fi
 
-duplicity $* $DUPLICITY_EXTRA_OPTS $DUPLICITY_BACKEND_URL
+command=$1
+shift
+
+usage() {
+    echo "$name - simple wrapper around duplicity recovery and management"
+    echo ""
+    echo "Usage:"
+    echo "   $name help"
+    echo "   $name (files|list-current-files) {options} # list files in backup set"
+    echo "   $name (sets|collection-status) {options}   # list backup set statuses"
+    echo "   $name restore {options} target_dir         # restore files to target_dir"
+    echo
+    echo "See duplicity(1) for specific command options"
+}
+
+case $command in
+  "help") { usage; exit 0; };;
+  "list-current-files") BASE_COMMAND="list-current-files" ;;
+  "files") BASE_COMMAND="list-current-files" ;;
+  "collection-status") BASE_COMMAND="collection-status" ;;
+  "sets") BASE_COMMAND="collection-status" ;;
+  "restore") BASE_COMMAND="restore" ;;
+  *) { echo "Unrecognised options: $*"; usage; exit 2; };;
+esac
+
+duplicity $BASE_COMMAND $DUPLICITY_EXTRA_OPTS $DUPLICITY_BACKEND_URL $*
